Traceback (most recent call last):
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn import linear_model
model = linear_model.LinearRegression(fit_intercept = False)
model.fit(X, y)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_20952/2661756792.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0msklearn[0m [1;32mimport[0m [0mlinear_model[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mmodel[0m [1;33m=[0m [0mlinear_model[0m[1;33m.[0m[0mLinearRegression[0m[1;33m([0m[0mfit_intercept[0m [1;33m=[0m [1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mmodel[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mX[0m[1;33m,[0m [0my[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'sklearn'
ModuleNotFoundError: No module named 'sklearn'

